TOP=../..
include $(TOP)/configure/CONFIG

DB += bkh01.db
DB += bkh03.db
DB += bkh04.db
DB += bkh05.db
DB += bkh07.db
DB += bkh08.db
DB += bkh09.db
DB += bkh10.db
DB += bkh11.db
DB += bkh12.db
DB += bkh13.db
DB += bkh14.db
DB += bkh15.db
DB += bkh16.db
DB += bkh17.db
DB += bkh18.db
DB += bkh19.db
DB += bkh21.db
DB += bkh22.db
DB += bkh23.db
DB += bkh24.db
DB += bkhMot15.db
DB += bkhMot21.db
DB += bkhMot23.db
DB += bkhMot24.db
DB += cha1.db
DB += chaMot1.db
DB += cha2.db
DB += chaMot2.db
DB += bkhSledSaveRestore.db
DB += bkh08Alias.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

